name: Building Package

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  release:
    types:
      - published

jobs:
  build:
    uses: openalea/github-action-conda-build/.github/workflows/openalea_ci.yml@main
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}

  